{% set version = "1.0.0" %}


package:
  name: r-leaflet.extras
  version: {{ version }}

source:
  fn: leaflet.extras_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/leaflet.extras_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/leaflet.extras/leaflet.extras_{{ version }}.tar.gz
  sha256: fc7b0611e6664d0e3e7e67b2e65555c6029727dc35b74ec0d3e753ce42312752

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-leaflet >=1.1.0
    - r-magrittr
    - r-shiny
    - r-stringr
  run:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-leaflet >=1.1.0
    - r-magrittr
    - r-shiny
    - r-stringr

test:
  commands:
    - $R -e "library('leaflet.extras')"  # [not win]
    - "\"%R%\" -e \"library('leaflet.extras')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/leaflet.extras
  license: GPL-3
  license_file: LICENSE
  summary: The 'leaflet' JavaScript library provides many plugins some of which are available
    in the core 'leaflet' package, but there are many more. It is not possible to support
    them all in the core 'leaflet' package. This package serves as an add-on to the
    'leaflet' package by providing extra functionality via 'leaflet' plugins.

extra:
  recipe-maintainers:
    - ocefpaf
