# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Bso8v8lQHXp8bXhpUfIHeHw5xtTXLvHtsVXqdfqWR4gk9D1japdlgltkMAzdOu/tVQu1Km51rP2SGl18N7Wu1VzUvBaczdR7gUQYVQxZnKzkWI2CNE0AuZvX6j0yKze3X96VLICYXxF4WkzdoLIZc7WruxpMwoD3oFRO6+gntSLYoW4lB9FowCZJpbjJIl1iR+LT516rLZTpsD/jBP+d/tCoRe1Y+jg3MSAmegVa5UFZUiHhwL97SP+j1LcSJoHEi2J9ykXSXLNns7FcpNUyM8W372fGDRmEC3iyqxNBPGJv2NYOtCel6Ltnv6yPqV/d0LCmVUUFC5auFw3WZF1kHk+NzrbfV5L9KkxtEGxr8rw5KXfH1t+h7dGqkR3fVCgYroOTKeFdcMb8gtAlru6bj7TIORcyvd3FefJpkl5NnDYBqqP/h9q+rk8dBqC00GyvDbLmAA7CkYMzlii5hW6Kw8AdqPGgIlW03K/gtlBdBj1aHgu+y7Y0/1Z+paQCs9mH5DXJrK1FRyFAwHZ8yM6+xXfdi+YyUfp/m8chn4yTVBWG6bYvxzqUvUSPiEXIQdP03JGOwoHQgsOD6QU47q3DIU8KCfhCphyyKSwTjGjWJbcQtiz9Jm9mMN2txLX0Bcm6XUmR9dfwl1qD8yxP9PndqaoEx6v+LqcXKqXj3jIcPyI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
