appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Bso8v8lQHXp8bXhpUfIHeHw5xtTXLvHtsVXqdfqWR4gk9D1japdlgltkMAzdOu/tVQu1Km51rP2SGl18N7Wu1VzUvBaczdR7gUQYVQxZnKzkWI2CNE0AuZvX6j0yKze3X96VLICYXxF4WkzdoLIZc7WruxpMwoD3oFRO6+gntSLYoW4lB9FowCZJpbjJIl1iR+LT516rLZTpsD/jBP+d/tCoRe1Y+jg3MSAmegVa5UFZUiHhwL97SP+j1LcSJoHEi2J9ykXSXLNns7FcpNUyM8W372fGDRmEC3iyqxNBPGJv2NYOtCel6Ltnv6yPqV/d0LCmVUUFC5auFw3WZF1kHk+NzrbfV5L9KkxtEGxr8rw5KXfH1t+h7dGqkR3fVCgYroOTKeFdcMb8gtAlru6bj7TIORcyvd3FefJpkl5NnDYBqqP/h9q+rk8dBqC00GyvDbLmAA7CkYMzlii5hW6Kw8AdqPGgIlW03K/gtlBdBj1aHgu+y7Y0/1Z+paQCs9mH5DXJrK1FRyFAwHZ8yM6+xXfdi+YyUfp/m8chn4yTVBWG6bYvxzqUvUSPiEXIQdP03JGOwoHQgsOD6QU47q3DIU8KCfhCphyyKSwTjGjWJbcQtiz9Jm9mMN2txLX0Bcm6XUmR9dfwl1qD8yxP9PndqaoEx6v+LqcXKqXj3jIcPyI=
conda_forge_output_validation: true
