travis:
  secure:
    BINSTAR_TOKEN: XkvdpPPBS+yyLlSozHI1oWRR0ESc8d93cH+GvC/RVO+OFbsXNS1x4HRVITmGAClo5+Z0X53fvB4laht9K0soGKP6Meov+GXFRSTzqPhtGL0j/v0XDopF0WyGKST7zxRbuUGm8Fee7qyOMyLcehEtBLVixfogrZcE6X160Jjq9WMgUxOgg/MtO75+rcJw+IR3HJCuQec3lWF2h+I2slzaa3pK/KTvnR6boHaBjsvAx2mPM7jJq9ql1uHTfhBZzo1FEeiTzrpnTFbDJKaB4RbvuAlYMd64+tG7Ks2BTSLPkCv4AEtwtFJc2UgRFu/x+X7UI2n5qC0TjDuuxsUKs42X6edwOwACsJXChGWH53SQaezG3sPSBOfSrFRpKetsvdv+4jzvHYSwTJ69+kwNF/spAVLUSt8+vsP+rHlx1OKjvGCnAtXWfx12qF0lBWCuBIAE3q0vXQ0kk7MS4KR7htmc0gWWPJN/Ay33/t5B3SxGC6cbHtnL9Q1tPZrvdzIlA+HLrjscS8rEDDyFZ6EGAm5kLg9aT4yGJfN7T/tyI1PdCJkghfiTk4LOlS4EqsLg2dGGZ642YLrr1WR5lzAg2KOcL6LoHFA8AxR72aWDK2MUZkur/7/z/cFq/CBjsGiORLEcuu48Tdc3XyPC5Ixfq2AoPcvlDZf4Mliru5GZiMDQnsM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
